apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-previews
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - pullRequest:
        github:
          owner: Ch4s3r
          repo: argocd-bootstrap-test
          tokenRef:
            secretName: argocd-notifications-secret
            key: github-token
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'pr-{{number}}'
      labels:
        preview: "true"
        pr-number: "{{number}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: staging
      source:
        repoURL: 'https://github.com/Ch4s3r/argocd-bootstrap-test'
        targetRevision: '{{head_sha}}'
        path: 'apps'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'staging'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
