apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-previews
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - pullRequest:
        github:
          owner: Ch4s3r
          repo: argocd-bootstrap-test
          tokenRef:
            secretName: argocd-notifications-secret
            key: github-token
        requeueAfterSeconds: 60
        filters:
          - paths:
              include:
                - 'apps/*/base/**'
                - 'apps/*/overlays/staging/**'
  template:
    metadata:
      name: 'pr-{{number}}-{{path[1]}}'
      labels:
        preview: "true"
        pr-number: "{{number}}"
        app-name: "{{path[1]}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
        notifications.argoproj.io/subscribe.on-deployed.github: ""
        notifications.argoproj.io/subscribe.on-deployment-failed.github: ""
    spec:
      project: staging
      source:
        repoURL: 'https://github.com/Ch4s3r/argocd-bootstrap-test'
        targetRevision: '{{head_sha}}'
        path: '{{path}}'
        kustomize:
          namespace: '{{path[3]}}-{{path[1]}}'
          namePrefix: 'pr-{{number}}-'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[3]}}-{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      # Automatically delete when PR is closed/merged
      info:
        - name: 'PR'
          value: 'https://github.com/Ch4s3r/argocd-bootstrap-test/pull/{{number}}'
        - name: 'Branch'
          value: '{{branch}}'
        - name: 'Application'
          value: '{{path[1]}}'
