apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-previews
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - matrix:
        generators:
          - pullRequest:
              github:
                owner: Ch4s3r
                repo: argocd-bootstrap-test
                tokenRef:
                  secretName: argocd-notifications-secret
                  key: github-token
              requeueAfterSeconds: 60
          - git:
              repoURL: 'https://github.com/Ch4s3r/argocd-bootstrap-test'
              revision: '{{head_sha}}'
              directories:
                - path: 'apps/*/overlays/staging'
  template:
    metadata:
      name: 'pr-{{number}}-{{path[1]}}'
      labels:
        preview: "true"
        pr-number: "{{number}}"
        app-name: "{{path[1]}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: staging
      source:
        repoURL: 'https://github.com/Ch4s3r/argocd-bootstrap-test'
        targetRevision: '{{head_sha}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[3]}}-{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
