apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-previews
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - name: hello-world
            namespace: staging-hello-world
            path: apps/hello-world/overlays/staging
          - name: argocd
            namespace: staging-argocd
            path: apps/argocd/overlays/staging
    - pullRequest:
        github:
          owner: Ch4s3r
          repo: argocd-bootstrap-test
          tokenRef:
            secretName: argocd-notifications-secret
            key: github-token
        requeueAfterSeconds: 60
  selector:
    matchExpressions:
      - key: pullrequest
        operator: In
        values:
          - "true"
  template:
    metadata:
      name: 'pr-{{number}}-{{name}}'
      labels:
        preview: "true"
        pr-number: "{{number}}"
        app-name: "{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: staging
      source:
        repoURL: 'https://github.com/Ch4s3r/argocd-bootstrap-test'
        targetRevision: '{{head_sha}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
