apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helmfile-releases
  namespace: argocd
spec:
  generators:
  - list:
      elements: []
  template:
    metadata:
      name: 'helmfile-{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Ch4s3r/argocd-bootstrap-test.git
        targetRevision: helmfile
        path: helmfile-test
        plugin:
          name: helmfile
          env:
          - name: HELMFILE_RELEASE
            value: '{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
